<?php

namespace Trp\MdlBundle\Repository;

/**
 * CmdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmdRepository extends \Doctrine\ORM\EntityRepository
{
}
