<?php

namespace Trp\MdlBundle\Repository;

/**
 * TcktRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TcktRepository extends \Doctrine\ORM\EntityRepository
{
}
